/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ergasiapsifiakesepikinonies;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author xaronai
 */
public class GUIforOneMessage extends javax.swing.JFrame {

    /**
     * Creates new form GUIforOneMessage
     */
    public GUIforOneMessage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageL = new javax.swing.JLabel();
        okB = new javax.swing.JButton();
        canselB = new javax.swing.JButton();
        divisorL = new javax.swing.JLabel();
        errorRateL = new javax.swing.JLabel();
        errorSp = new javax.swing.JSpinner();
        textForMT = new javax.swing.JTextField();
        textForPT = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        helpB = new javax.swing.JMenuItem();
        aboutB = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        messageL.setText("Message:");

        okB.setText("OK");
        okB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBActionPerformed(evt);
            }
        });

        canselB.setText("Cansel");
        canselB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canselBActionPerformed(evt);
            }
        });

        divisorL.setText("Divisor:");

        errorRateL.setText("Error Rate:");

        errorSp.setModel(new javax.swing.SpinnerNumberModel(1.23d, 0.0d, 100.0d, 0.01d));
        errorSp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                errorSpKeyTyped(evt);
            }
        });

        textForMT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textForMTKeyTyped(evt);
            }
        });

        textForPT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textForPTKeyTyped(evt);
            }
        });

        jMenu1.setText("Help");

        helpB.setText("Help");
        helpB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBActionPerformed(evt);
            }
        });
        jMenu1.add(helpB);

        aboutB.setText("About");
        aboutB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBActionPerformed(evt);
            }
        });
        jMenu1.add(aboutB);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(canselB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(messageL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(divisorL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errorRateL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textForMT, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textForPT, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorSp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageL)
                    .addComponent(textForMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divisorL)
                    .addComponent(textForPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorRateL)
                    .addComponent(errorSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okB)
                    .addComponent(canselB))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void errorSpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_errorSpKeyTyped
        char c=evt.getKeyChar(); //get input from text field character by character
        if (!((c >= '0') && (c <= '1') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_errorSpKeyTyped

    private void textForMTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textForMTKeyTyped
        char c=evt.getKeyChar(); //get input from text field character by character
        if (!((c >= '0') && (c <= '1') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))){
            getToolkit().beep(); //consume them if they are not binary numbers
            evt.consume();
        }
    }//GEN-LAST:event_textForMTKeyTyped

    private void textForPTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textForPTKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textForPTKeyTyped

    private void canselBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canselBActionPerformed
        GUIergasias temp= new GUIergasias();
        temp.setEnabled(true);
        temp.setVisible(true);
        dispose();
    }//GEN-LAST:event_canselBActionPerformed

    private void okBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBActionPerformed
        Boolean ranThatB= true;
        if (textForPT.getText().equals("")||textForMT.getText().equals("")) {
            int n = JOptionPane.showConfirmDialog(null, ""
                    + "TheFields are empty. Press \"yes\""
                    + "\nto return to main program or press"
                    + "\n\"no\" to fill up the fields",
                    "Security message", JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.YES_OPTION) {
                ranThatB= true;
            } else if (n == JOptionPane.NO_OPTION) {
                ranThatB= false;
            }
            if(!ranThatB){

            }else if(ranThatB){
                GUIergasias temp= new GUIergasias();
                temp.setEnabled(true);
                temp.setVisible(true);
                dispose();
            }
        }else{
            GUIergasias temp= new GUIergasias();
            temp.setEnabled(true);
            temp.setVisible(true);
            temp.getter(evt, textForMT.getText(), Integer.toString(textForMT.getText().length()),textForPT.getText(),(double) errorSp.getValue());
            dispose();
        }
    }//GEN-LAST:event_okBActionPerformed

    private void helpBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBActionPerformed
        JOptionPane.showMessageDialog(null, ""
                + "Put the message you want to CRC in"
                + "\nthe first field, the divisor in the"
                + "\nsecond field, the error rate on the"
                + "\nspinner and press \"OK\"."
                + "\nYou need to fill up the fields or"
                + "\nyou will be asked to refill them or"
                + "\nreturn to the main GUI.", "Help message", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_helpBActionPerformed

    private void aboutBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBActionPerformed
        JOptionPane.showMessageDialog(null, "Ergasia stis Psifiakes Epikinonies.\n"
            + "Georgios Kirmitsakis\nAEM: 2449", "About", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_aboutBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIforOneMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIforOneMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIforOneMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIforOneMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIforOneMessage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutB;
    private javax.swing.JButton canselB;
    private javax.swing.JLabel divisorL;
    private javax.swing.JLabel errorRateL;
    private javax.swing.JSpinner errorSp;
    private javax.swing.JMenuItem helpB;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel messageL;
    private javax.swing.JButton okB;
    private javax.swing.JTextField textForMT;
    private javax.swing.JTextField textForPT;
    // End of variables declaration//GEN-END:variables
}
